---
- hosts: web
  become: true
  become_user: root
  tasks:
  - name: Uninstalling jenkins
    yum:
      name: jenkins
      state: absent
  - name: stoping jenkins
    service:
      name: jenkins
      state: stopped
